# Generated by Django 6.0.2 on 2026-02-24 13:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_category', models.CharField(choices=[('spring', '春リーグ'), ('autumn', '秋リーグ'), ('other', 'その他')], max_length=20, verbose_name='大会カテゴリ')),
                ('competition_name', models.CharField(blank=True, max_length=100, verbose_name='大会名')),
                ('opponent_name', models.CharField(max_length=100, verbose_name='対戦相手')),
                ('match_datetime', models.DateTimeField(verbose_name='試合日時')),
                ('venue_name', models.CharField(max_length=100, verbose_name='会場名')),
                ('status', models.CharField(choices=[('scheduled', '予定'), ('finished', '終了'), ('cancelled', '中止')], default='scheduled', max_length=20, verbose_name='ステータス')),
                ('result_outcome', models.CharField(choices=[('win', '勝ち'), ('lose', '負け'), ('draw', '引き分け'), ('none', '未定')], default='none', max_length=20, verbose_name='勝敗')),
                ('score_kyodai_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='京大 合計')),
                ('score_opponent_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='相手 合計')),
                ('score_kyodai_first_half', models.PositiveIntegerField(blank=True, null=True, verbose_name='京大 前半')),
                ('score_opponent_first_half', models.PositiveIntegerField(blank=True, null=True, verbose_name='相手 前半')),
                ('score_kyodai_second_half', models.PositiveIntegerField(blank=True, null=True, verbose_name='京大 後半')),
                ('score_opponent_second_half', models.PositiveIntegerField(blank=True, null=True, verbose_name='相手 後半')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開する')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='表タイトル（例: 2024年 春リーグ）')),
                ('competition_category', models.CharField(choices=[('spring', '春リーグ'), ('autumn', '秋リーグ'), ('other', 'その他')], max_length=20)),
                ('table_data', wagtail.fields.StreamField([('table', 0)], block_lookup={0: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'renderer': 'html'}})}, verbose_name='星取表')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
