# Generated by Django 6.0.2 on 2026-02-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchentry',
            name='competition_name',
            field=models.CharField(blank=True, help_text='「その他」を選択した場合は、ここに大会名（例: 西日本インカレ、七大戦など）を入力してください', max_length=100, verbose_name='大会名'),
        ),
    ]
