# Generated by Django 6.0.2 on 2026-02-26 08:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_matchentry_competition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhubpage',
            name='past_records',
            field=wagtail.fields.StreamField([('record', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': '例: 2025年度', 'label': '年度'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': '戦績詳細'}), 2: ('wagtail.blocks.StructBlock', [[('year', 0), ('details', 1)]], {'label': '過去の戦績'})}, verbose_name='過去の戦績まとめ'),
        ),
    ]
