# Generated by Django 6.0.2 on 2026-02-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchhubpage_past_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchentry',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='配信やハイライトのURLがあれば入力してください', verbose_name='YouTubeリンク'),
        ),
    ]
