# Generated by Django 6.0.2 on 2026-02-24 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga4_measurement_id', models.CharField(blank=True, help_text='例: G-XXXXXXXXXX', max_length=50)),
                ('contact_form_url', models.URLField(blank=True, help_text='GoogleフォームのURL')),
                ('sponsor_form_url', models.URLField(blank=True, help_text='スポンサー用GoogleフォームのURL')),
                ('instagram_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'サイト全体設定',
            },
        ),
    ]
