# Generated by Django 6.0.2 on 2026-02-27 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_youtube_url'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スポンサー名')),
                ('url', models.URLField(blank=True, help_text='クリック時の飛び先', verbose_name='リンク先URL')),
                ('display_order', models.IntegerField(default=0, help_text='数字が小さいほど左に表示されます', verbose_name='表示順')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開する')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='ロゴ画像')),
            ],
            options={
                'verbose_name': 'スポンサー',
                'verbose_name_plural': 'スポンサー一覧',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
