# Generated by Django 6.0.2 on 2026-02-24 13:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('practice_schedule', wagtail.fields.RichTextField(blank=True, help_text='例: 火・木 17:00~19:00 / 土 9:00~12:00', verbose_name='通常練習日程')),
                ('location', wagtail.fields.RichTextField(blank=True, verbose_name='活動場所')),
                ('monthly_schedule', wagtail.fields.RichTextField(blank=True, help_text='1月〜12月の予定をリストで記載してください', verbose_name='年間スケジュール')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(verbose_name='本文')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
