# Generated by Django 6.0.2 on 2026-02-26 08:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_activitiespage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiespage',
            name='club_profile',
            field=wagtail.fields.RichTextField(blank=True, help_text='所属や部員数などを記入してください', verbose_name='クラブプロフィール'),
        ),
    ]
