# Generated by Django 6.0.2 on 2026-03-03 02:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activitiespage_club_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiespage',
            name='vision_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='チームの活動目的やスローガン、目標などを記入してください', verbose_name='チーム目標・ビジョン'),
        ),
    ]
