# Generated by Django 6.0.2 on 2026-02-26 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日時'),
        ),
    ]
