# Generated by Django 6.0.2 on 2026-02-24 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('role_type', models.CharField(choices=[('player', '選手'), ('manager', 'マネージャー')], default='player', max_length=20, verbose_name='役職')),
                ('grade', models.CharField(help_text='例: 3回生', max_length=20, verbose_name='学年')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='ポジション')),
                ('hometown', models.CharField(blank=True, max_length=50, verbose_name='出身地/出身校')),
                ('profile_text', models.TextField(blank=True, verbose_name='紹介文')),
                ('display_order', models.IntegerField(default=0, help_text='数字が小さいほど上に表示されます', verbose_name='表示順')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開する')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
