# Generated by Django 6.0.2 on 2026-02-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='intro_url',
            field=models.URLField(blank=True, help_text='クリック時の飛び先URL（空欄の場合はリンクになりません）', verbose_name='紹介記事のURL'),
        ),
    ]
