# Generated by Django 6.0.2 on 2026-02-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_intro_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='背番号'),
        ),
    ]
