# Generated by Django 6.0.2 on 2026-03-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'メンバー', 'verbose_name_plural': 'メンバー一覧'},
        ),
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, help_text='例: 工学部、〇〇女子大学', max_length=50, verbose_name='学部/所属大学'),
        ),
    ]
